### ISSUE TITLE
Find out how to use tabbed content with sphinx

### ISSUE THREAD

**Issue by rluce** [rluce/nupstup#3]
Use case: switch between prose descritption of model, and mathjax standard OR description

**Comment by simonbowly** [comment]
[sphinx-tabs](https://sphinx-tabs.readthedocs.io/en/latest/) looks promising. This is what cython uses in their docs and snippets can be included direct from source files into restructured text like so:

```
.. tabs::
    .. group-tab:: Pure Python

        .. literalinclude:: ../../examples/tutorial/cython_tutorial/primes.py
            :linenos:
            :caption: primes.py

    .. group-tab:: Cython

        .. literalinclude:: ../../examples/tutorial/cython_tutorial/primes.pyx
            :linenos:
            :caption: primes.pyx
```

**Comment by simonbowly** [comment]
We may not need `group-tab`, just `tab`. group-tab links everything across the page, i.e. in the cython docs, all tabs switch language together so that you have a consistent theme. For our use case, we'll probably have a math vs dataframes tab and a model store vs gurobipy tab. See https://github.com/rluce/nupstup/blob/main/docs/source/library/workforce.rst
